### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by wgfrhebnr** [Francis0625/Omni-SR#10]
Hi！
I don't understand the file structure of the data set. 
Can you tell me its file structure as shown below?

DIV2K
├── DIV2K_test_LR_bicubic
│   ├── X2
│   │   ├── 0901x2.png
│   │   ├─ ...
│   │   └── 1000x2.png
│   ├── X3
│   │   ├── 0901x3.png
│   │   ├─ ...
│   │   └── 1000x3.png
│   └── X4
│       ├── 0901x4.png
│        ├─ ...
│       └── 1000x4.png
├── DIV2K_test_LR_unknown
│   ├── X2
│   │   ├── 0901x2.png
│   │   ├─ ...
│   │   └── 1000x2.png
│   ├── X3
│   │   ├── 0901x3.png
│   │   ├─ ...
│   │   └── 1000x3.png
│   └── X4
│       ├── 0901x4.png
│       ├─ ...
│       └── 1000x4.png
├── DIV2K_train_HR
│   ├── 0001.png
│   ├─ ...
│   └── 0900.png
├── DIV2K_train_LR_bicubic
│   ├── X2
│   │   ├── 0001x2.png
│   │   ├─ ...
│   │   └── 0900x2.png
│   ├── X3
│   │   ├── 0001x3.png
│   │   ├─ ...
│   │   └── 0900x3.png
│   └── X4
│       ├── 0001x4.png
│       ├─ ...
│       └── 0900x4.png
└── DIV2K_train_LR_unknown
    ├── X2
    │   ├── 0001x2.png
    │   ├─ ...
    │   └── 0900x2.png
    ├── X3
    │   ├── 0001x3.png
    │   ├─ ...
    │   └── 0900x3.png
    └── X4
        ├── 0001x4.png
        ├─ ...
        └── 0900x4.png

**Comment by Francis0625** [comment]
I think this file structure is correct. Here is a example, "DIV2K_train_LR_bicubic\X4\0001x4.png". Make sure the dataset root path in env.json is right!
