### ISSUE TITLE
Thank you :)

### ISSUE THREAD

**Issue by Phhofm** [Francis0625/Omni-SR#13]
I just wanted to show real quick, [chaiNNer](https://github.com/chaiNNer-org/chaiNNer) had added OmniSR so people can simply upscale a single image with an OmniSR model using this gui application. We also started trying out this network by training our own models.

I recently trained a 2x OmniSR anime upscaling model that handles AVC (h264) compression. These are simply two examples
https://imgsli.com/MTg2ODcz
https://imgsli.com/MTg2ODc1

The model file can be found [here](https://github.com/Phhofm/models/tree/main/2xHFA2kAVCOmniSR). There is also another community trained OmniSR model released by musl before this one called 4x_ardo ([example1](https://cdn.discordapp.com/attachments/579685650824036387/1117897320521011321/4x_ardo_cmp_4.png), [example2](https://cdn.discordapp.com/attachments/579685650824036387/1117897318771986543/4x_ardo_cmp_0.png)). I just thought it might be interesting for you to see that (and how) your network is being used, this is why I wrote this :) Thank you for your work :)

**Comment by neuralchen** [comment]
Good work
