### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by wgfrhebnr** [Francis0625/Omni-SR#6]
Hi! I'm interested in your work. 

When I was running the program, I encountered a problem:
ValueError: num_samples should be a positive integer value, but got num_samples=0

How can I solve this problem?

**Comment by Francis0625** [comment]
Can you provide more information about the problem?

**Comment by wgfrhebnr** [comment]
The questions are as follows：

(OmniSR) chenz@chenz-System-Product-Name:~/OmniSR$ python train.py -v "OmniSR_X4_DIV2K" -p train --train_yaml "train_OmniSR_X4_DIV2K.yaml"
Start to run training script: train_scripts.trainer_common
Traning version: OmniSR_X4_DIV2K
Dataloader Name: DIV2K_memory
Batch size: 64
Prepare the train dataloader...
processing DIV2K images...
Finished preprocessing the DIV2K dataset, total image number: 0...
0it [00:00, ?it/s]
Finish to read the dataset!
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    main()
  File "train.py", line 214, in main
    trainer     = trainerClass(sys_state, reporter)
  File "/home/chenz/OmniSR/train_scripts/trainer_common.py", line 43, in __init__
    dataloader      = dataloaderClass(train_dataset,
  File "/home/chenz/OmniSR/data_tools/dataloader_DIV2K_memory.py", line 218, in GetLoader
    content_data_loader = data.DataLoader(
  File "/home/chenz/anaconda3/envs/OmniSR/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 344, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/home/chenz/anaconda3/envs/OmniSR/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0


Hope to get your answer.

**Comment by wgfrhebnr** [comment]
@Francis0625

**Comment by Francis0625** [comment]
可能的原因：传入的Dataset中的len(self.data_info)==0，即传入该dataloader的dataset里没有数据

解决方法：检查dataset中的路径，路径不对，读取不到数据。

**Comment by wgfrhebnr** [comment]
请问能否给出具体的数据集数据结构（文件集关系）？我不清楚是不是我哪里弄错了？

**Comment by wgfrhebnr** [comment]
@Francis0625

**Comment by Francis0625** [comment]
If you set the path of the dataset correctly, the code will output "Finished preprocessing the DIV2K dataset, total image number: 800."
