### ISSUE TITLE
What is the difference between Meso-OSA and GlobalOSA?

### ISSUE THREAD

**Issue by haikunzhang95** [Francis0625/Omni-SR#9]
- How to understand the window division strategy of Meso-OSA and GlobalOSA? In my opinion, aren't they all divided into blocks? Looking forward to your answer, thank you!

**Comment by Francis0625** [comment]
Window partition strategies make the difference. As shown in Figure 4,  Meso-OSA splits the input feature into non-overlapping blocks, while Global-OSA divides the input feature into a uniform grid.

**Comment by chenglih** [comment]
代码中为啥没有区别
